In [48]:
import pandas as pd

In [49]:
marks=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','e'])
print(marks)
print(type(marks.loc['e']))
marks.iloc[1:3]

a    1
b    2
c    3
d    4
e    5
e    6
dtype: int64
<class 'pandas.Series'>

b    2
c    3
dtype: int64

In [50]:
data={
    'Name': ['A', 'B', 'C'],
    'Marks': [85, 90, 78],
    'City': ['Ahmedabad', 'Delhi', 'Mumbai']
}

df=pd.DataFrame(data)
df

  Name  Marks       City
0    A     85  Ahmedabad
1    B     90      Delhi
2    C     78     Mumbai

In [51]:
df=pd.read_csv('auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [52]:
s1=pd.Series([1,2,3])
s2=pd.Series(["a","b","c"])

df=pd.DataFrame({"col1":s1,"col2":s2})

In [53]:
df.reset_index(inplace=True)

In [54]:
print(df)

   index  col1 col2
0      0     1    a
1      1     2    b
2      2     3    c

In [55]:
df=pd.read_csv("auto-mpg.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [56]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [57]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(3), int64(4), str(2)
memory usage: 28.1 KB

In [59]:
df.shape

(398, 9)

In [60]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='str')

In [61]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight            int64
acceleration    float64
model year        int64
origin            int64
car name            str
dtype: object

In [62]:
df.sample

<bound method NDFrame.sample of       mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]>

In [63]:
import pandas as pd
import numpy as np

data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Marks': [85, np.nan, 78, 90],
    'City': ['Ahmedabad', 'Delhi', None, 'Mumbai']
}

df=pd.DataFrame(data)
print(df)
print(df.isna())
print(df.isna().sum())
print("drop")
df2=df.dropna(how='any')
print(df2)
print("drop all")
df2=df.dropna(how='all')
print(df2)
df2=df.dropna(thresh=3)
print(df2)

  Name  Marks       City
0    A   85.0  Ahmedabad
1    B    NaN      Delhi
2    C   78.0        NaN
3    D   90.0     Mumbai
    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
Name     0
Marks    1
City     1
dtype: int64
drop
  Name  Marks       City
0    A   85.0  Ahmedabad
3    D   90.0     Mumbai
drop all
  Name  Marks       City
0    A   85.0  Ahmedabad
1    B    NaN      Delhi
2    C   78.0        NaN
3    D   90.0     Mumbai
  Name  Marks       City
0    A   85.0  Ahmedabad
3    D   90.0     Mumbai

In [64]:
df['Marks']=df['Marks'].fillna(0)
df['City']=df["City"].fillna("Unknown")
print(df)

  Name  Marks       City
0    A   85.0  Ahmedabad
1    B    0.0      Delhi
2    C   78.0    Unknown
3    D   90.0     Mumbai

In [65]:
print(df)

  Name  Marks       City
0    A   85.0  Ahmedabad
1    B    0.0      Delhi
2    C   78.0    Unknown
3    D   90.0     Mumbai

In [66]:
print(df['Marks'].fillna(0))

0    85.0
1     0.0
2    78.0
3    90.0
Name: Marks, dtype: float64

In [67]:
df.loc[1,'Marks']=0

In [68]:
print(df)

  Name  Marks       City
0    A   85.0  Ahmedabad
1    B    0.0      Delhi
2    C   78.0    Unknown
3    D   90.0     Mumbai

In [69]:
df.loc[3,"Marks"]

np.float64(90.0)

In [70]:
df.loc[0:4]

  Name  Marks       City
0    A   85.0  Ahmedabad
1    B    0.0      Delhi
2    C   78.0    Unknown
3    D   90.0     Mumbai

In [71]:
df.iloc[0,2]

'Ahmedabad'

In [72]:
import pandas as pd

data = {
    "name": ["Kohli", "Rohit", "Gill", "Rahul"],
    "runs": [12000, 11000, 3500, 4200],
    "average": [59.5, 48.7, 51.2, 45.3]
}

df = pd.DataFrame(data,index=["A","B","C","D"])
print(df)
print("Edit")
df.loc["A":"C", ["runs", "average1"]] = [13000, 60]
print(df)

    name   runs  average
A  Kohli  12000     59.5
B  Rohit  11000     48.7
C   Gill   3500     51.2
D  Rahul   4200     45.3
Edit
    name   runs  average  average1
A  Kohli  13000     59.5      60.0
B  Rohit  13000     48.7      60.0
C   Gill  13000     51.2      60.0
D  Rahul   4200     45.3       NaN

In [73]:
df['performance']='good'
df.loc[df["average"]<50,'performance']='average'

In [74]:
df

    name   runs  average  average1 performance
A  Kohli  13000     59.5      60.0        good
B  Rohit  13000     48.7      60.0     average
C   Gill  13000     51.2      60.0        good
D  Rahul   4200     45.3       NaN     average

In [75]:
df

    name   runs  average  average1 performance
A  Kohli  13000     59.5      60.0        good
B  Rohit  13000     48.7      60.0     average
C   Gill  13000     51.2      60.0        good
D  Rahul   4200     45.3       NaN     average

In [76]:
df.drop('average1',axis=1,inplace=True)

In [77]:
df

    name   runs  average performance
A  Kohli  13000     59.5        good
B  Rohit  13000     48.7     average
C   Gill  13000     51.2        good
D  Rahul   4200     45.3     average

In [78]:
data = {
    'Name': ['A', 'B', 'A', 'C'],
    'Marks': [85, 90, 85, 78]
}

df = pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    A     85
3    C     78

In [79]:
print(df.duplicated())
df2=df.drop_duplicates()
df2

0    False
1    False
2     True
3    False
dtype: bool

  Name  Marks
0    A     85
1    B     90
3    C     78

In [80]:
df.drop_duplicates(keep='first',inplace=True)

In [81]:
df.sort_index(ascending=False)

  Name  Marks
3    C     78
1    B     90
0    A     85

In [82]:
df.sort_values(by='Marks')

  Name  Marks
3    C     78
0    A     85
1    B     90

In [83]:
df[(df['Marks']>80) & (df['Marks']<90)]

  Name  Marks
0    A     85

In [84]:
data = {
    'City': ['Ahmedabad', 'Delhi', 'Delhi', 'Mumbai', 'Ahmedabad']
}

df = pd.DataFrame(data)
df['City'].unique()

<StringArray>
['Ahmedabad', 'Delhi', 'Mumbai']
Length: 3, dtype: str

In [85]:
x=df['City'].value_counts()

In [86]:
data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Marks': [85, 92, 78, 88]
}
df=pd.DataFrame(data)

print(df.describe(include='all'))

print(df.describe(exclude='int64'))

       Name      Marks
count     4   4.000000
unique    4        NaN
top       A        NaN
freq      1        NaN
mean    NaN  85.750000
std     NaN   5.909033
min     NaN  78.000000
25%     NaN  83.250000
50%     NaN  86.500000
75%     NaN  89.000000
max     NaN  92.000000
       Name
count     4
unique    4
top       A
freq      1

In [87]:
import pandas as pd

data = {
    'Department': ['IT', 'HR', 'IT', 'HR', 'Finance'],
    'Employee': ['A', 'B', 'C', 'D', 'E'],
    'Salary': [50000, 40000, 60000, 45000, 70000]
}

df = pd.DataFrame(data)

In [88]:
result=df.groupby('Department')['Salary'].agg(['sum','min','mean'])
print(result)

               sum    min     mean
Department
Finance      70000  70000  70000.0
HR           85000  40000  42500.0
IT          110000  50000  55000.0

In [89]:
data = {
    "Department": ["IT", "IT", "HR", "HR", "Finance", "IT"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Salary": [50000, 60000, 45000, 48000, 70000, 55000],
    "Experience": [2, 3, 1, 2, 5, 4]
}

df = pd.DataFrame(data)
print(df)

df.groupby(['Department','Experience'],as_index=False)['Salary'].sum()

  Department Employee  Salary  Experience
0         IT        A   50000           2
1         IT        B   60000           3
2         HR        C   45000           1
3         HR        D   48000           2
4    Finance        E   70000           5
5         IT        F   55000           4

  Department  Experience  Salary
0    Finance           5   70000
1         HR           1   45000
2         HR           2   48000
3         IT           2   50000
4         IT           3   60000
5         IT           4   55000

In [90]:
df.groupby("Department")[["Salary","Experience"]].sum()

            Salary  Experience
Department
Finance      70000           5
HR           93000           3
IT          165000           9

In [91]:
df.groupby('Department')['Salary'].apply(lambda x: x.max()-x.min())

Department
Finance        0
HR          3000
IT         10000
Name: Salary, dtype: int64

In [92]:
df.groupby("Department").head()

  Department Employee  Salary  Experience
0         IT        A   50000           2
1         IT        B   60000           3
2         HR        C   45000           1
3         HR        D   48000           2
4    Finance        E   70000           5
5         IT        F   55000           4

In [93]:
import pandas as pd
import numpy as np

# 1. Create a sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'A'],
    'Value': [10, 20, 10, 30, 40, 20, 10, 40],
    'Region': ['East', 'West', 'East', 'East', 'West', 'West', 'East', 'East']
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("-" * 30)

# 2. Group by 'Category' and count the number of unique 'Value' entries in each group
# The result will be a pandas Series
unique_counts_series = df.groupby('Category')['Value'].nunique()

print("Unique counts per Category (pandas Series):")
print(unique_counts_series)
print("-" * 30)

Original DataFrame:
  Category  Value Region
0        A     10   East
1        B     20   West
2        A     10   East
3        B     30   East
4        A     40   West
5        B     20   West
6        A     10   East
7        A     40   East
------------------------------
Unique counts per Category (pandas Series):
Category
A    2
B    2
Name: Value, dtype: int64
------------------------------

In [94]:
df['Value'].unique()

array([10, 20, 30, 40])

In [95]:
import pandas as pd

df1 = pd.DataFrame({
    "Maths": [80, 85, 90],
    "Science": [78, 82, 88],
    "English": [70, 75, 80]
})

result = df1.apply(lambda x:x.mean())
print(result)

Maths      85.000000
Science    82.666667
English    75.000000
dtype: float64

In [96]:
df1

   Maths  Science  English
0     80       78       70
1     85       82       75
2     90       88       80

In [97]:
df3 = pd.DataFrame({
    "Sub1": [50, 60, 70],
    "Sub2": [55, 65, 75],
    "Sub3": [60, 70, 80]
})

result = df3.apply(lambda x: x.sum(), axis=1)
print(result)

0    165
1    195
2    225
dtype: int64

In [98]:
df5 = pd.DataFrame({
    "Marks1": [85, 70, 90],
    "Marks2": [80, 65, 95],
    "Marks3": [75, 60, 85]
})


def grade(total):
    if total >= 250:
        return "A"
    elif total >= 200:
        return "B"
    else:
        return "C"
    
df5['Total']=df5.apply(lambda x:x.sum(),axis=1)
df5['Grade']=df5["Total"].apply(grade)

print(df5)

   Marks1  Marks2  Marks3  Total Grade
0      85      80      75    240     B
1      70      65      60    195     C
2      90      95      85    270     A

In [7]:
import pandas as pd
df7 = pd.DataFrame({
    "Marks": [80, 90, 85],
    "Bonus": [5, 10, 5],
    "Penalty": [2, 1, 3]
})

result = df7.apply(
    lambda x: [x.sum(), x.mean()],
    axis=1,
    result_type='expand'
)

print(result)

       0          1
0   87.0  29.000000
1  101.0  33.666667
2   93.0  31.000000

In [21]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

result = pd.concat([df1, df2],axis=1)
print(result)
print(pd.concat([df1, df2], join='outer',axis=0))
#All columns from both DataFrames are included:outer
#Only common columns are included.:inner
print(pd.concat([df1, df2], join='inner'))
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
pd.concat([df1, df2], join='inner')

   A  B
0  1  3
1  2  4
     A    B
0  1.0  NaN
1  2.0  NaN
0  NaN  3.0
1  NaN  4.0
Empty DataFrame
Columns: []
Index: [0, 1, 0, 1]

   A
0  1
1  2
0  3
1  4